name: NPM Publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin...
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install
        env:
          CI: true

      - name: Test
        run: yarn test
        env:
          REDIS: ${{ secrets.TEST_REDIS }}
          MONGO: ${{ secrets.TEST_MONGO }}

      - name: Version
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Publish
        run: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc && npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
